### ISSUE TITLE
Doctests in Munch fork don't run correctly

### ISSUE THREAD

**Issue by femtotrader** [dsc/bunch#24]
Hello,

I try this fork of Bunch which seems interesting
https://github.com/Infinidat/munch

but Doctests don't run (never failed)

For example I changed:

        >>> [ (k,b[k]) for k in b ]
        [('ponies', 'are pretty!'), ('foo', Munch(lol=True)), ('hello', 42)]

to

        >>> [ (k,b[k]) for k in b ]
        [('ponies', 'are prettyERROR!'), ('foo', Munch(lol=True)), ('hello', 42)]

and no error raised (which is a problem as it should raise an error)

**Comment by femtotrader** [comment]
nosetests gives no error but nosetests -s -v gives 2 failing tests

@vmalloc Any idea ?

    pc:munch scls$ nosetests
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.089s

    OK

    pc:munch me$ nosetests -s -v
    tests.test_doctests.test ... Trying:
        b = Munch()
    Expecting nothing
    ok
    Trying:
        b.hello = 'world'
    Expecting nothing
    ok
    Trying:
        b.hello
    Expecting:
        'world'
    ok
    Trying:
        b['hello'] += "!"
    Expecting nothing
    ok
    Trying:
        b.hello
    Expecting:
        'world!'
    ok
    Trying:
        b.foo = Munch(lol=True)
    Expecting nothing
    ok
    Trying:
        b.foo.lol
    Expecting:
        True
    ok
    Trying:
        b.foo is b['foo']
    Expecting:
        True
    ok
    Trying:
        b = Munch()
    Expecting nothing
    ok
    Trying:
        b.hello = 'world'
    Expecting nothing
    ok
    Trying:
        b.hello
    Expecting:
        'world'
    ok
    Trying:
        b['hello'] += "!"
    Expecting nothing
    ok
    Trying:
        b.hello
    Expecting:
        'world!'
    ok
    Trying:
        b.foo = Munch(lol=True)
    Expecting nothing
    ok
    Trying:
        b.foo.lol
    Expecting:
        True
    ok
    Trying:
        b.foo is b['foo']
    Expecting:
        True
    ok
    Trying:
        sorted(b.keys())
    Expecting:
        ['foo', 'hello']
    ok
    Trying:
        b.update({ 'ponies': 'are pretty!' }, hello=42)
    Expecting nothing
    ok
    Trying:
        print (repr(b))
    Expecting:
        Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    ok
    Trying:
        [ (k,b[k]) for k in b ]
    Expecting:
        [('ponies', 'are pretty!'), ('foo', Munch(lol=True)), ('hello', 42)]
    ok
    Trying:
        "The {knights} who say {ni}!".format(**Munch(knights='lolcats', ni='can haz'))
    Expecting:
        'The lolcats who say can haz!'
    ok
    Trying:
        b = Munch(ponies='are pretty!')
    Expecting nothing
    ok
    Trying:
        'ponies' in b
    Expecting:
        True
    ok
    Trying:
        'foo' in b
    Expecting:
        False
    ok
    Trying:
        b['foo'] = 42
    Expecting nothing
    ok
    Trying:
        'foo' in b
    Expecting:
        True
    ok
    Trying:
        b.hello = 'hai'
    Expecting nothing
    ok
    Trying:
        'hello' in b
    Expecting:
        True
    ok
    Trying:
        b[None] = 123
    Expecting nothing
    ok
    Trying:
        None in b
    Expecting:
        True
    ok
    Trying:
        b[False] = 456
    Expecting nothing
    ok
    Trying:
        False in b
    Expecting:
        True
    ok
    Trying:
        b = Munch(lol=42)
    Expecting nothing
    ok
    Trying:
        del b.values
    Expecting:
        Traceback (most recent call last):
            ...
        AttributeError: 'Munch' object attribute 'values' is read-only
    **********************************************************************
    File "/Users/scls/github/others/munch/munch/__init__.py", line 163, in munch.Munch.__delattr__
    Failed example:
        del b.values
    Expected:
        Traceback (most recent call last):
            ...
        AttributeError: 'Munch' object attribute 'values' is read-only
    Got:
        Traceback (most recent call last):
          File "//anaconda/lib/python3.4/doctest.py", line 1318, in __run
            compileflags, 1), test.globs)
          File "<doctest munch.Munch.__delattr__[1]>", line 1, in <module>
            del b.values
          File "/Users/scls/github/others/munch/munch/__init__.py", line 182, in __delattr__
            object.__delattr__(self, k)
        AttributeError: values
    Trying:
        del b.lol
    Expecting nothing
    ok
    Trying:
        b.lol
    Expecting:
        Traceback (most recent call last):
            ...
        AttributeError: lol
    ok
    Trying:
        b = Munch(bar='baz', lol={})
    Expecting nothing
    ok
    Trying:
        b.foo
    Expecting:
        Traceback (most recent call last):
            ...
        AttributeError: foo
    ok
    Trying:
        b.bar
    Expecting:
        'baz'
    ok
    Trying:
        getattr(b, 'bar')
    Expecting:
        'baz'
    ok
    Trying:
        b['bar']
    Expecting:
        'baz'
    ok
    Trying:
        b.lol is b['lol']
    Expecting:
        True
    ok
    Trying:
        b.lol is getattr(b, 'lol')
    Expecting:
        True
    ok
    Trying:
        b = Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    Expecting nothing
    ok
    Trying:
        print (repr(b))
    Expecting:
        Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    ok
    Trying:
        eval(repr(b))
    Expecting:
        Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    ok
    Trying:
        b = Munch(foo='bar', this_is='useful when subclassing')
    Expecting nothing
    ok
    Trying:
        b.values                            #doctest: +ELLIPSIS
    Expecting:
        <built-in method values of Munch object at 0x...>
    ok
    Trying:
        b.values = 'uh oh'
    Expecting nothing
    ok
    Trying:
        b.values
    Expecting:
        'uh oh'
    ok
    Trying:
        b['values']
    Expecting:
        Traceback (most recent call last):
            ...
        KeyError: 'values'
    ok
    Trying:
        b = Munch.fromDict({'urmom': {'sez': {'what': 'what'}}})
    Expecting nothing
    ok
    Trying:
        b.urmom.sez.what
    Expecting:
        'what'
    ok
    Trying:
        b = Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    Expecting nothing
    ok
    Trying:
        b.toDict()
    Expecting:
        {'ponies': 'are pretty!', 'foo': {'lol': True}, 'hello': 42}
    ok
    Trying:
        b = Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    Expecting nothing
    ok
    Trying:
        json.dumps(b)
    Expecting:
        '{"ponies": "are pretty!", "foo": {"lol": true}, "hello": 42}'
    ok
    Trying:
        b.toJSON()
    Expecting:
        '{"ponies": "are pretty!", "foo": {"lol": true}, "hello": 42}'
    ok
    Trying:
        b = Munch(foo=['bar', Munch(lol=True)], hello=42)
    Expecting nothing
    ok
    Trying:
        import yaml
    Expecting nothing
    ok
    Trying:
        yaml.safe_dump(b, default_flow_style=True)
    Expecting:
        '{foo: [bar, {lol: true}], hello: 42}\n'
    ok
    Trying:
        b.toYAML(default_flow_style=True)
    Expecting:
        '{foo: [bar, {lol: true}], hello: 42}\n'
    ok
    Trying:
        yaml.dump(b, default_flow_style=True)
    Expecting:
        '!munch.Munch {foo: [bar, !munch.Munch {lol: true}], hello: 42}\n'
    ok
    Trying:
        b.toYAML(Dumper=yaml.Dumper, default_flow_style=True)
    Expecting:
        '!munch.Munch {foo: [bar, !munch.Munch {lol: true}], hello: 42}\n'
    ok
    Trying:
        import yaml
    Expecting nothing
    ok
    Trying:
        yaml.load('''
        Flow style: !munch.Munch { Clark: Evans, Brian: Ingerson, Oren: Ben-Kiki }
        Block style: !munch
          Clark : Evans
          Brian : Ingerson
          Oren  : Ben-Kiki
        ''') #doctest: +NORMALIZE_WHITESPACE
    Expecting:
        {'Flow style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki'),
         'Block style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki')}
    **********************************************************************
    File "/Users/scls/github/others/munch/munch/__init__.py", line 326, in munch.from_yaml
    Failed example:
        yaml.load('''
        Flow style: !munch.Munch { Clark: Evans, Brian: Ingerson, Oren: Ben-Kiki }
        Block style: !munch
          Clark : Evans
          Brian : Ingerson
          Oren  : Ben-Kiki
        ''') #doctest: +NORMALIZE_WHITESPACE
    Expected:
        {'Flow style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki'),
         'Block style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki')}
    Got:
        {'Block style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki'), 'Flow style': Munch(Brian='Ingerson', Clark='Evans', Oren='Ben-Kiki')}
    Trying:
        b = munchify({'urmom': {'sez': {'what': 'what'}}})
    Expecting nothing
    ok
    Trying:
        b.urmom.sez.what
    Expecting:
        'what'
    ok
    Trying:
        b = munchify({ 'lol': ('cats', {'hah':'i win again'}),
                'hello': [{'french':'salut', 'german':'hallo'}] })
    Expecting nothing
    ok
    Trying:
        b.hello[0].french
    Expecting:
        'salut'
    ok
    Trying:
        b.lol[1].hah
    Expecting:
        'i win again'
    ok
    Trying:
        b = Munch(foo=['bar', Munch(lol=True)], hello=42)
    Expecting nothing
    ok
    Trying:
        import yaml
    Expecting nothing
    ok
    Trying:
        yaml.dump(b, default_flow_style=True)
    Expecting:
        '!munch.Munch {foo: [bar, !munch.Munch {lol: true}], hello: 42}\n'
    ok
    Trying:
        b = Munch(foo=['bar', Munch(lol=True)], hello=42)
    Expecting nothing
    ok
    Trying:
        import yaml
    Expecting nothing
    ok
    Trying:
        yaml.safe_dump(b, default_flow_style=True)
    Expecting:
        '{foo: [bar, {lol: true}], hello: 42}\n'
    ok
    Trying:
        b = Munch(foo=Munch(lol=True), hello=42, ponies='are pretty!')
    Expecting nothing
    ok
    Trying:
        unmunchify(b)
    Expecting:
        {'ponies': 'are pretty!', 'foo': {'lol': True}, 'hello': 42}
    ok
    Trying:
        b = Munch(foo=['bar', Munch(lol=True)], hello=42,
                ponies=('are pretty!', Munch(lies='are trouble!')))
    Expecting nothing
    ok
    Trying:
        unmunchify(b) #doctest: +NORMALIZE_WHITESPACE
    Expecting:
        {'ponies': ('are pretty!', {'lies': 'are trouble!'}),
         'foo': ['bar', {'lol': True}], 'hello': 42}
    ok
    2 items had no tests:
        munch.Munch.__members__
        munch.Munch.fromYAML
    14 items passed all tests:
       8 tests in munch
      13 tests in munch.Munch
      11 tests in munch.Munch.__contains__
       7 tests in munch.Munch.__getattr__
       3 tests in munch.Munch.__repr__
       5 tests in munch.Munch.__setattr__
       2 tests in munch.Munch.fromDict
       2 tests in munch.Munch.toDict
       3 tests in munch.Munch.toJSON
       6 tests in munch.Munch.toYAML
       5 tests in munch.munchify
       3 tests in munch.to_yaml
       3 tests in munch.to_yaml_safe
       4 tests in munch.unmunchify
    **********************************************************************
    2 items had failures:
       1 of   4 in munch.Munch.__delattr__
       1 of   2 in munch.from_yaml
    81 tests in 18 items.
    79 passed and 2 failed.
    ***Test Failed*** 2 failures.
    ok
    tests.test_munch.test_dir ... ok

    ----------------------------------------------------------------------
    Ran 2 tests in 0.093s

    OK

**Comment by vmalloc** [comment]
Once again, works in munch... https://github.com/Infinidat/munch

**Comment by vmalloc** [comment]
I don't know why you opened this here -- if this is a munch issue you should open it in Munch itself. In any case it uses py.test and not nose...

**Comment by femtotrader** [comment]
Because you need to enable Issue in Munch repository
because when you fork a project on GitHub by default forked project doesn't have bug tracker enabled.

so you need (our someone from your org) to go to
https://github.com/Infinidat/munch/settings
and enable Features / Issues

**Comment by vmalloc** [comment]
Whoops! I just enabled it. Sorry!

**Comment by femtotrader** [comment]
Thanks.
Closed
