### ISSUE TITLE
infi.bunch package raises AttributeError: type object 'dict' has no attribute 'iteritems'

### ISSUE THREAD

**Issue by femtotrader** [dsc/bunch#33]
Hi @vmalloc 

see this Travis build https://travis-ci.org/ig-python/ig-markets-api-python-library/jobs/83294568
(using Python 3)

        from infi.bunch import bunchify
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/infi/bunch/__init__.py", line 31, in <module>
        from .python3_compat import *
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/infi/bunch/python3_compat.py", line 20, in <module>
        iteritems = dict.iteritems
    AttributeError: type object 'dict' has no attribute 'iteritems'

Any idea ?

I think your `python3_compat.py` is wrong and Python 3 is recognized as Python 2.

Kind regards

**Comment by femtotrader** [comment]
Your pip package should be updated

    $ pip install infi.bunch
    Collecting infi.bunch
    Installing collected packages: infi.bunch
    Successfully installed infi.bunch-2.0.0
    pc:pyside2-setup scls$ cat /anaconda/lib/python3.4/site-packages/infi/bunch/python3_compat.py
    import platform

    _IS_PYTHON_3 = (platform.version() >= '3')

    identity = lambda x : x

    # u('string') replaces the forwards-incompatible u'string'
    if _IS_PYTHON_3:
        u = identity
    else:
        import codecs
        def u(string):
            return codecs.unicode_escape_decode(string)[0]

    # dict.iteritems(), dict.iterkeys() is also incompatible
    if _IS_PYTHON_3:
        iteritems = dict.items
        iterkeys  = dict.keys
    else:
        iteritems = dict.iteritems
        iterkeys = dict.iterkeys

but

in https://github.com/Infinidat/munch it's 

    import sys

    _PY2 = (sys.version_info < (3,0))

    identity = lambda x : x

    # u('string') replaces the forwards-incompatible u'string'
    if _PY2:
        import codecs
        def u(string):
            return codecs.unicode_escape_decode(string)[0]
    else:
        u = identity

    # dict.iteritems(), dict.iterkeys() is also incompatible
    if _PY2:
        iteritems = dict.iteritems
        iterkeys = dict.iterkeys
    else:
        iteritems = dict.items
        iterkeys  = dict.keys

**Comment by duffar12** [comment]
@femtotrader did you get a solution to this? I'm getting the same error...

**Comment by vmalloc** [comment]
@duffar12 which bunch are you using? `bunch` is no longer maintained...

**Comment by duffar12** [comment]
I'm using @femtotrader's ig-python library. It depends on infi.bunch 2.0.0

**Comment by android-programmer** [comment]
@femtotrader did you get a solution to this? I'm getting the same error...

I'm using @femtotrader's ig-python library. It depends on infi.bunch 2.0.0

**Comment by mtastan** [comment]
One way to solve this: 

Locate python3.4/site-packages/infi/bunch/python3_compat.py

Then replace "if _IS_PYTHON_3:" to "if not _IS_PYTHON_3:"

It should work now. This has worked for me. The issue is this: Since (platform.version() >= '3') returns "False", infi recognizes your python version as "2" by mistake if you guys are using python 3 +.
