### ISSUE TITLE
Add support to python 3

### ISSUE THREAD

**Issue by maxiplux** [dsc/bunch#48]
My friend thanks for this amazing library , but please would be possible add support to python 3.
I think that is only change iteritems by items() , return Bunch( (k, bunchify(v)) for k,v in items(x) ) .
thanks

**Comment by jaraco** [comment]
Dupe of #17

**Comment by dachshund-digital** [comment]
Come on... Python2 is DEAD, not supporting Python3, really?

**Comment by mnaielksu1** [comment]
I did the following changes in ```/python3.8/site-packages/bunch/__init__.py``` to support Python3:
Line 245:  ```return Bunch( (k, bunchify(v)) for k,v in x.items() )```  
Line 270:  ```return dict( (k, unbunchify(v)) for k,v in x.items() )```

Now ```from bunch import bunchify``` is working.
