### ISSUE TITLE
Python 3 testing should be not

### ISSUE THREAD

**Issue by ishahak** [dsc/bunch#55]
I'm suspecting that the coverage for python 2 (which I use as CircuitPython) is broken. the 'if' and 'else' should be swapped:

https://github.com/dsc/bunch/blob/34eedf58fae929b3bb017338d24e978156dafa2b/bunch/python3_compat.py#L16

because in Python 2, you can't say
iteritems = dict.iteritems
iterkeys = dict.iterkeys

as dict doesn't include them

**Comment by dsc** [comment]
Yep. This has been fixed.
