### ISSUE TITLE
bunch 1.0.1 is not compatible with python 3.11

### ISSUE THREAD

**Issue by cjkrolak** [dsc/bunch#56]
in setup.py line 11:

```
package_file = open(join(HERE, 'bunch/__init__.py'), 'rU')
```

"U" option for universal newline is no longer supported in python 3.11

**Comment by wilbertom** [comment]
I'm forking here for python 3 only: https://github.com/wilbertom/bunch-py3

**Comment by rrauenza** [comment]
Note that there appears to be another fork at https://github.com/Infinidat/munch , whichis what @cjkrolak ended up using.

**Comment by dsc** [comment]
These have all been fixed and I'm talking to `munch` about merging our projects.
